version: '3.8'

services:
  web:
    build: .
    ports:
      - "7861:7860"
    volumes:
      - .:/app
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped
    env_file:
      - .env
